
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "java/junit5"
    schedule:
      interval: "weekly"
#./java/hamcrest/build.gradle
#./java/jqwik/build.gradle
#./java/junit5/build.gradle
#./java/junit4/build.gradle
#./java/truth/build.gradle
#./java/fitnesse/myapp/build.gradle
#./java/fitnesse/atests/build.gradle
#./java/fitnesse/build.gradle
#./java/hue4j5/build.gradle
#./kotlin/spek/build.gradle
#./kotlin/kotlintest/build.gradle
#./kotlin/spock/build.gradle
  - package-ecosystem: "maven"
    directory: "java/"
    schedule:
      interval: "weekly"

#./java/hamcrest/pom.xml
#./java/jqwik/pom.xml
#./java/cucumber/pom.xml
#./java/junit5/pom.xml
#./java/junit4/pom.xml
#./java/truth/pom.xml
#./java/spock/pom.xml
#./java/hue4j5/pom.xml
#./kotlin/junit/pom.xml

  - package-ecosystem: "npm"
    directory: "ts/typescript-jest"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: ""
    schedule:
      interval: "weekly"
